CREATE DATABASE GameSite

GO
USE GameSite
GO

CREATE LOGIN GameUser WITH PASSWORD = 'admin';

CREATE USER GameUser FROM LOGIN GameUser;

ALTER ROLE db_owner ADD MEMBER GameUser;

CREATE TABLE Usuarios (
	IDUsuario INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Usuario NVARCHAR (50) NOT NULL,
	Nombre NVARCHAR (50) NOT NULL,
	Apellido NVARCHAR (50) NOT NULL,
	Mail NVARCHAR (100) NOT NULL,
	Pass NVARCHAR (50) NOT NULL
);
GO